apiVersion: batch/v1
kind: Job
metadata:
  labels:
    metrics-infra: hawkular-metrics
    name: hawkular-metrics-schema
  name: hawkular-metrics-schema
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: hawkular-metrics-schema
    spec:
      containers:
      - env:
        - name: TRUSTSTORE_AUTHORITIES
          value: /hawkular-metrics-certs/tls.truststore.crt
        image: registry.redhat.io/openshift3/metrics-schema-installer:v3.11.153
        imagePullPolicy: IfNotPresent
        name: hawkular-metrics-schema
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hawkular-metrics-certs
          name: hawkular-metrics-certs
        - mountPath: /hawkular-account
          name: hawkular-metrics-account
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hawkular-metrics-certs
        secret:
          defaultMode: 420
          secretName: hawkular-metrics-certs
      - name: hawkular-metrics-account
        secret:
          defaultMode: 420
          secretName: hawkular-metrics-account
status: {}
